/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package orienteering

import org.junit.jupiter.api.Test
import orienteering.data.InstanceDto
import kotlin.test.assertEquals
import kotlin.test.assertNull

class InstanceTests {
    @Test fun `instance reading`() {
        val instance = InstanceDto(
                "p2.2.a.txt",
                "./data/Set_21_234/",
                2, 1.0).getInstance()
        assertEquals(instance.budget, 7.5)
        assertEquals(instance.numTargets, 23)
        assertEquals(instance.numVertices, 44)
        assertEquals(instance.sourceTarget, 21)
        assertEquals(instance.destinationTarget, 22)
        assertEquals(instance.getAdjacentVertices(40)!!.size, 1)
        assertEquals(instance.getAdjacentVertices(42)!!.size, 2)
        assertNull(instance.getAdjacentVertices(43))
    }

}
